theme: jekyll-theme-minimal
title: dabell-cc's homepage
description: This will get flushed out eventually...
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

